#!/bin/bash

echo $1 | build/lisp > build/test.out
echo $1 >  build/test.expected 
echo $2 >> build/test.expected
if ! diff build/test.expected build/test.out > build/test.diff ; then
   echo "Test failed"
   echo "-- Diff "
   cat build/test.diff
   echo "-- Obtained output"
   cat build/test.out
   echo "--"
fi 
   
